[package]
name = "sclunerbot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.10.10"
tokio = { version = "1.16.1", features = ["rt-multi-thread"] }
rand = "0.8.4"
bitap = "0.2.0"
lazy_static = "1.4.0"
chrono = "0.4.19"
